# Generated by Django 6.0.4 on 2026-04-22 08:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('menus', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('normal', 'Commande normale'), ('anonymous', 'Commande anonyme'), ('for_other', 'Pour un tiers'), ('off_menu', 'Hors menu')], default='normal', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('off_menu_description', models.TextField(blank=True, help_text='Description si commande hors menu')),
                ('off_menu_price', models.PositiveIntegerField(default=0, help_text='Prix en tickets')),
                ('for_person_name', models.CharField(blank=True, help_text='Nom de la personne si commande pour tiers', max_length=200)),
                ('for_person_phone', models.CharField(blank=True, max_length=50)),
                ('for_person_department', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('preparing', 'En préparation'), ('ready', 'Prêt'), ('delivered', 'Livré'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('delivery_notes', models.TextField(blank=True, help_text='Instructions de livraison')),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivered_orders', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='employees.employee')),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='menus.dailymenu')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='orders_meal_status_b58f53_idx'), models.Index(fields=['employee', 'status'], name='orders_meal_employe_f29539_idx')],
            },
        ),
    ]
