# Generated by Django 6.0.4 on 2026-04-22 02:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('menus', '0002_menucategory_remove_dailymenu_photo_and_more'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealorder',
            old_name='for_person',
            new_name='for_person_name',
        ),
        migrations.RemoveField(
            model_name='mealorder',
            name='is_anonymous',
        ),
        migrations.RemoveField(
            model_name='mealorder',
            name='special_instructions',
        ),
        migrations.AddField(
            model_name='mealorder',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mealorder',
            name='delivered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivered_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mealorder',
            name='delivery_notes',
            field=models.TextField(blank=True, help_text='Instructions de livraison'),
        ),
        migrations.AddField(
            model_name='mealorder',
            name='for_person_department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='mealorder',
            name='for_person_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='mealorder',
            name='off_menu_description',
            field=models.TextField(blank=True, help_text='Description si commande hors menu'),
        ),
        migrations.AddField(
            model_name='mealorder',
            name='off_menu_price',
            field=models.PositiveIntegerField(default=0, help_text='Prix en tickets'),
        ),
        migrations.AddField(
            model_name='mealorder',
            name='order_type',
            field=models.CharField(choices=[('normal', 'Commande normale'), ('anonymous', 'Commande anonyme'), ('for_other', 'Pour un tiers'), ('off_menu', 'Hors menu')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='mealorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mealorder',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='mealorder',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='menus.dailymenu'),
        ),
        migrations.AlterField(
            model_name='mealorder',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='mealorder',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('preparing', 'En préparation'), ('ready', 'Prêt'), ('delivered', 'Livré'), ('cancelled', 'Annulé')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='mealorder',
            index=models.Index(fields=['status', 'created_at'], name='orders_meal_status_b58f53_idx'),
        ),
        migrations.AddIndex(
            model_name='mealorder',
            index=models.Index(fields=['employee', 'status'], name='orders_meal_employe_f29539_idx'),
        ),
    ]
