# Generated by Django 6.0.4 on 2026-04-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/%Y/%m/%d/', verbose_name='photo de profil'),
        ),
    ]
