# Generated by Django 6.0.4 on 2026-04-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('monthly', 'Rapport mensuel'), ('provider', 'Rapport prestataire'), ('employee', 'Rapport employé'), ('financial', 'Rapport financier')], max_length=50)),
                ('period', models.CharField(help_text='Mois ou année concerné', max_length=20)),
                ('data', models.JSONField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['report_type', 'period'], name='reporting_r_report__871b61_idx')],
            },
        ),
    ]
