# Generated by Django 6.0.4 on 2026-04-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='téléphone')),
                ('address', models.TextField(blank=True, verbose_name='adresse')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='ville')),
                ('country', models.CharField(default='Togo', max_length=100, verbose_name='pays')),
                ('ticket_value', models.DecimalField(decimal_places=2, default=1000, max_digits=10, verbose_name='valeur du ticket')),
                ('employee_percentage', models.DecimalField(decimal_places=2, default=40, max_digits=5, verbose_name='part employé (%)')),
                ('company_percentage', models.DecimalField(decimal_places=2, default=60, max_digits=5, verbose_name='part entreprise (%)')),
                ('default_quota', models.PositiveIntegerField(default=30, verbose_name='quota mensuel')),
                ('ticket_validity_days', models.PositiveIntegerField(default=90, verbose_name='validité tickets')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
            },
        ),
    ]
