# Generated by Django 6.0.4 on 2026-04-22 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approved', 'Approuvé'), ('refused', 'Refusé')], max_length=20, verbose_name='décision')),
                ('comment', models.TextField(blank=True, verbose_name='commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de décision')),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_logs', to='purchases.purchaserequest', verbose_name="demande d'achat")),
                ('validator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_logs', to=settings.AUTH_USER_MODEL, verbose_name='validateur')),
            ],
            options={
                'verbose_name': 'journal de validation',
                'verbose_name_plural': 'journaux de validation',
                'ordering': ['-created_at'],
            },
        ),
    ]
