# Generated by Django 6.0.4 on 2026-04-21 23:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_tickets', models.PositiveIntegerField(default=0, verbose_name='tickets actifs')),
                ('used_tickets_month', models.PositiveIntegerField(default=0, verbose_name='tickets utilisés ce mois')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='dernière mise à jour')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='employees.employee', verbose_name='employé')),
            ],
            options={
                'verbose_name': 'solde employé',
                'verbose_name_plural': 'soldes employés',
            },
        ),
        migrations.CreateModel(
            name='TicketLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Nombre de tickets dans le lot', verbose_name='quantité')),
                ('unit_value', models.DecimalField(decimal_places=2, help_text="Valeur monétaire d'un ticket", max_digits=10, verbose_name='valeur unitaire')),
                ('employee_part', models.DecimalField(decimal_places=2, help_text="Montant payé par l'employé par ticket", max_digits=10, verbose_name='part employé')),
                ('company_part', models.DecimalField(decimal_places=2, help_text="Montant payé par l'entreprise par ticket", max_digits=10, verbose_name='part entreprise')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Montant total du lot', max_digits=10, verbose_name='montant total')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('expires_at', models.DateTimeField(help_text='Date à laquelle les tickets expirent', verbose_name="date d'expiration")),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_lots', to='employees.employee', verbose_name='employé')),
            ],
            options={
                'verbose_name': 'lot de tickets',
                'verbose_name_plural': 'lots de tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_code', models.CharField(default=uuid.uuid4, editable=False, max_length=50, unique=True, verbose_name='code unique')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('used', 'Utilisé'), ('expired', 'Expiré')], default='active', max_length=20, verbose_name='statut')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name="date d'utilisation")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tickets.ticketlot', verbose_name='lot')),
            ],
            options={
                'verbose_name': 'ticket',
                'verbose_name_plural': 'tickets',
                'ordering': ['lot__created_at', 'id'],
            },
        ),
    ]
