# Generated by Django 6.0.4 on 2026-04-21 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='icône')),
            ],
            options={
                'verbose_name': 'catégorie',
                'verbose_name_plural': 'catégories',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('commercial_name', models.CharField(blank=True, max_length=200, verbose_name='nom commercial')),
                ('registration_number', models.CharField(blank=True, max_length=100, verbose_name="numéro d'enregistrement")),
                ('tax_id', models.CharField(blank=True, max_length=100, verbose_name='numéro fiscal')),
                ('contact_person', models.CharField(blank=True, max_length=200, verbose_name='personne de contact')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='téléphone')),
                ('alternative_phone', models.CharField(blank=True, max_length=50, verbose_name='téléphone alternatif')),
                ('address', models.TextField(blank=True, default='', verbose_name='adresse')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='ville')),
                ('country', models.CharField(default='Togo', max_length=100, verbose_name='pays')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='code postal')),
                ('payment_methods', models.JSONField(blank=True, default=list, verbose_name='modes de paiement')),
                ('contract_number', models.CharField(blank=True, max_length=100, verbose_name='numéro de contrat')),
                ('contract_start', models.DateField(blank=True, null=True, verbose_name='début contrat')),
                ('contract_end', models.DateField(blank=True, null=True, verbose_name='fin contrat')),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='contracts/%Y/%m/', verbose_name='fichier contrat')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('rating', models.DecimalField(decimal_places=2, default=0, help_text='Note sur 5', max_digits=3, verbose_name='note')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('is_preferred', models.BooleanField(default=False, verbose_name='partenaire privilégié')),
                ('total_tickets_sold', models.PositiveIntegerField(default=0, verbose_name='total tickets vendus')),
                ('total_amount_due', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='total dû')),
                ('total_amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='total payé')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date modification')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='providers_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'prestataire',
                'verbose_name_plural': 'prestataires',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProviderSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nom du site')),
                ('code', models.CharField(blank=True, max_length=50, unique=True, verbose_name='code du site')),
                ('address', models.TextField(verbose_name='adresse')),
                ('city', models.CharField(max_length=100, verbose_name='ville')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='quartier')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='longitude')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='téléphone')),
                ('manager_name', models.CharField(blank=True, max_length=200, verbose_name='nom du responsable')),
                ('manager_phone', models.CharField(blank=True, max_length=50, verbose_name='téléphone du responsable')),
                ('opening_hours', models.JSONField(blank=True, default=dict, verbose_name="horaires d'ouverture")),
                ('capacity', models.PositiveIntegerField(default=0, verbose_name='capacité (couverts)')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('is_main_site', models.BooleanField(default=False, verbose_name='site principal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date modification')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='providers.provider', verbose_name='prestataire')),
            ],
            options={
                'verbose_name': 'site prestataire',
                'verbose_name_plural': 'sites prestataires',
                'ordering': ['provider__name', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['name'], name='providers_p_name_44a164_idx'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['is_active'], name='providers_p_is_acti_7dfa8f_idx'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['city'], name='providers_p_city_95c2e9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='providersite',
            unique_together={('provider', 'code')},
        ),
    ]
