# Generated by Django 6.0.4 on 2026-04-22 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumption',
            name='created_by',
        ),
    ]
