# Generated by Django 6.0.4 on 2026-04-21 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='nombre de tickets')),
                ('ticket_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valeur unitaire du ticket')),
                ('employee_part', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='part employé')),
                ('company_part', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='part entreprise')),
                ('total_employee_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='montant total employé')),
                ('total_company_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='montant total entreprise')),
                ('status', models.CharField(choices=[('pending', 'En attente de validation'), ('approved', 'Approuvé'), ('refused', 'Refusé'), ('cancelled', 'Annulé'), ('delivered', 'Tickets attribués')], default='pending', max_length=20, verbose_name='statut')),
                ('payment_method', models.CharField(blank=True, choices=[('moov', 'Moov Money'), ('tmoney', 'TMoney'), ('flooz', 'Flooz'), ('bank', 'Virement bancaire'), ('cash', 'Espèces')], max_length=20, verbose_name='mode de paiement')),
                ('payment_reference', models.CharField(blank=True, max_length=100, verbose_name='référence de paiement')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='date de paiement')),
                ('payment_proof', models.FileField(blank=True, help_text="Capture d'écran ou reçu de paiement", null=True, upload_to='payment_proofs/%Y/%m/%d/', verbose_name='preuve de paiement')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='date de validation')),
                ('refusal_reason', models.TextField(blank=True, verbose_name='motif de refus')),
                ('validation_comment', models.TextField(blank=True, verbose_name='commentaire de validation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to='employees.employee', verbose_name='employé')),
                ('ticket_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_request', to='tickets.ticketlot', verbose_name='lot de tickets attribué')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_purchases', to=settings.AUTH_USER_MODEL, verbose_name='validé par')),
            ],
            options={
                'verbose_name': "demande d'achat",
                'verbose_name_plural': "demandes d'achat",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='payment_proofs/%Y/%m/%d/', verbose_name='fichier')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='nom du fichier')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='taille du fichier')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='type MIME')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name="date d'upload")),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_proofs', to=settings.AUTH_USER_MODEL)),
                ('purchase_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proof', to='purchases.purchaserequest', verbose_name="demande d'achat")),
            ],
            options={
                'verbose_name': 'preuve de paiement',
                'verbose_name_plural': 'preuves de paiement',
            },
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['status', 'created_at'], name='purchases_p_status_e74967_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['employee', 'status'], name='purchases_p_employe_84d5b9_idx'),
        ),
    ]
