# Generated by Django 6.0.4 on 2026-04-22 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('payment_method', models.CharField(blank=True, choices=[('moov', 'Moov Money'), ('mixx_by_yas', 'Mixx By Yas'), ('flooz', 'Flooz'), ('bank', 'Virement bancaire'), ('cash', 'Espèces')], max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('payment_proof', models.FileField(blank=True, null=True, upload_to='payment_proofs/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('pending', 'En attente de validation'), ('approved', 'Approuvé'), ('refused', 'Refusé'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('ticket_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('employee_part', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('company_part', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_employee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_company_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('refusal_reason', models.TextField(blank=True)),
                ('validation_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to='employees.employee')),
                ('ticket_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_request', to='tickets.ticketlot')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
