# Generated by Django 6.0.4 on 2026-04-22 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('purchases', '0001_initial'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentproof',
            name='purchase_request',
        ),
        migrations.RemoveField(
            model_name='paymentproof',
            name='uploaded_by',
        ),
        migrations.AlterModelOptions(
            name='purchaserequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='purchaserequest',
            name='purchases_p_status_e74967_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchaserequest',
            name='purchases_p_employe_84d5b9_idx',
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='company_part',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='employee_part',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('moov', 'Moov Money'), ('mixx_by_yas', 'Mixx By Yas'), ('flooz', 'Flooz'), ('bank', 'Virement bancaire'), ('cash', 'Espèces')], max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='payment_proof',
            field=models.FileField(blank=True, null=True, upload_to='payment_proofs/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='refusal_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente de validation'), ('approved', 'Approuvé'), ('refused', 'Refusé'), ('cancelled', 'Annulé')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='ticket_lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_request', to='tickets.ticketlot'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='ticket_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='total_company_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='total_employee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='validation_comment',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='PaymentProof',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='payment_date',
        ),
    ]
