# Generated by Django 6.0.4 on 2026-04-22 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_quota', models.PositiveIntegerField(default=30, help_text='Quota mensuel par défaut pour les nouveaux employés', verbose_name='quota par défaut')),
                ('max_quota', models.PositiveIntegerField(default=50, help_text='Quota mensuel maximum autorisé', verbose_name='quota maximum')),
                ('ticket_value', models.DecimalField(decimal_places=2, default=1000, help_text="Valeur monétaire d'un ticket en FCFA", max_digits=10, verbose_name='valeur du ticket')),
                ('employee_percentage', models.DecimalField(decimal_places=2, default=40, help_text="Pourcentage du ticket payé par l'employé", max_digits=5, verbose_name='part employé (%)')),
                ('company_percentage', models.DecimalField(decimal_places=2, default=60, help_text="Pourcentage du ticket payé par l'entreprise", max_digits=5, verbose_name='part entreprise (%)')),
                ('ticket_validity_days', models.PositiveIntegerField(default=90, help_text='Nombre de jours de validité des tickets après achat', verbose_name='validité des tickets (jours)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'configuration des quotas',
                'verbose_name_plural': 'configurations des quotas',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='département')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='poste')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='téléphone professionnel')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name="date d'embauche")),
                ('monthly_ticket_quota', models.PositiveIntegerField(default=30, help_text="Nombre maximum de tickets que l'employé peut obtenir par mois", verbose_name='quota mensuel de tickets')),
                ('current_month_tickets', models.PositiveIntegerField(default=0, help_text='Nombre de tickets achetés dans le mois en cours', verbose_name='tickets achetés ce mois')),
                ('last_quota_reset', models.DateField(auto_now_add=True, help_text='Date du dernier réinitialisation du quota mensuel', verbose_name='dernier reset du quota')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='companies.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'employé',
                'verbose_name_plural': 'employés',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
    ]
