# Generated by Django 6.0.4 on 2026-04-22 08:07

import apps.menus.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MenuDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], unique=True)),
                ('deadline_time', models.TimeField(help_text='Heure limite de commande')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['weekday'],
            },
        ),
        migrations.CreateModel(
            name='DailyMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price_tickets', models.PositiveIntegerField(default=1, help_text='Nombre de tickets requis', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('main_photo', models.ImageField(blank=True, help_text='Photo principale du menu', null=True, upload_to=apps.menus.models.menu_photo_path)),
                ('additional_photos', models.JSONField(blank=True, default=list, help_text='Photos supplémentaires (URLs)')),
                ('is_available', models.BooleanField(default=True)),
                ('max_orders_per_day', models.PositiveIntegerField(default=0, help_text='0 = illimité')),
                ('order_start_time', models.TimeField(default='08:00', help_text='Début des commandes')),
                ('order_end_time', models.TimeField(default='10:30', help_text='Fin des commandes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='providers.provider')),
            ],
            options={
                'ordering': ['-date', 'provider'],
                'indexes': [models.Index(fields=['date', 'is_available'], name='menus_daily_date_82ae78_idx'), models.Index(fields=['provider', 'date'], name='menus_daily_provide_d75f4a_idx')],
                'unique_together': {('provider', 'date')},
            },
        ),
    ]
