# Generated by Django 6.0.4 on 2026-04-22 02:12

import apps.menus.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
        ('providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='dailymenu',
            name='photo',
        ),
        migrations.AddField(
            model_name='dailymenu',
            name='additional_photos',
            field=models.JSONField(blank=True, default=list, help_text='Photos supplémentaires (URLs)'),
        ),
        migrations.AddField(
            model_name='dailymenu',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailymenu',
            name='main_photo',
            field=models.ImageField(blank=True, help_text='Photo principale du menu', null=True, upload_to=apps.menus.models.menu_photo_path),
        ),
        migrations.AddField(
            model_name='dailymenu',
            name='max_orders_per_day',
            field=models.PositiveIntegerField(default=0, help_text='0 = illimité'),
        ),
        migrations.AddField(
            model_name='dailymenu',
            name='order_end_time',
            field=models.TimeField(default='10:30', help_text='Fin des commandes'),
        ),
        migrations.AddField(
            model_name='dailymenu',
            name='order_start_time',
            field=models.TimeField(default='08:00', help_text='Début des commandes'),
        ),
        migrations.AddField(
            model_name='dailymenu',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='menudeadline',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='price_tickets',
            field=models.PositiveIntegerField(default=1, help_text='Nombre de tickets requis', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='menudeadline',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], unique=True),
        ),
        migrations.AddIndex(
            model_name='dailymenu',
            index=models.Index(fields=['date', 'is_available'], name='menus_daily_date_82ae78_idx'),
        ),
        migrations.AddIndex(
            model_name='dailymenu',
            index=models.Index(fields=['provider', 'date'], name='menus_daily_provide_d75f4a_idx'),
        ),
    ]
