# Generated by Django 6.0.4 on 2026-04-24 22:10

import apps.menus.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('menus', '0001_initial'),
        ('providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menucategory',
            options={'ordering': ['order'], 'verbose_name': 'Catégorie de menu', 'verbose_name_plural': 'Catégories de menus'},
        ),
        migrations.AlterModelOptions(
            name='menudeadline',
            options={'ordering': ['weekday'], 'verbose_name': 'Heure limite', 'verbose_name_plural': 'Heures limites'},
        ),
        migrations.AddField(
            model_name='menucategory',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_categories', to='companies.company'),
        ),
        migrations.AddField(
            model_name='menudeadline',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_deadlines', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='additional_photos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='main_photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.menus.models.menu_photo_path),
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='order_end_time',
            field=models.TimeField(default='10:30'),
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='order_start_time',
            field=models.TimeField(default='08:00'),
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='price_tickets',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_menus', to='providers.provider'),
        ),
        migrations.AlterField(
            model_name='menucategory',
            name='icon',
            field=models.CharField(blank=True, max_length=50, verbose_name='Icône'),
        ),
        migrations.AlterField(
            model_name='menucategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom de la catégorie'),
        ),
        migrations.AlterField(
            model_name='menucategory',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage"),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du plat')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('meal_type', models.CharField(choices=[('main', 'Plat principal'), ('starter', 'Entrée'), ('dessert', 'Dessert'), ('drink', 'Boisson'), ('side', 'Accompagnement')], default='main', max_length=20, verbose_name='Type de plat')),
                ('price_tickets', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Prix en tickets')),
                ('price_fcfa', models.PositiveIntegerField(default=0, verbose_name='Prix en FCFA')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=apps.menus.models.menu_photo_path, verbose_name='Photo principale')),
                ('additional_photos', models.JSONField(blank=True, default=list, verbose_name='Photos supplémentaires')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('is_daily', models.BooleanField(default=False, verbose_name='Menu du jour')),
                ('available_date', models.DateField(blank=True, null=True, verbose_name='Date de disponibilité')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock disponible')),
                ('max_per_order', models.PositiveIntegerField(default=10, verbose_name='Maximum par commande')),
                ('max_orders_per_day', models.PositiveIntegerField(default=0, verbose_name='Maximum commandes par jour (0 = illimité)')),
                ('order_start_time', models.TimeField(default='08:00', verbose_name='Début des commandes')),
                ('order_end_time', models.TimeField(default='10:30', verbose_name='Fin des commandes')),
                ('total_orders', models.PositiveIntegerField(default=0, verbose_name='Total commandes')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menus', to='menus.menucategory', verbose_name='Catégorie')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='companies.company', verbose_name='Entreprise')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='providers.provider', verbose_name='Prestataire')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
                'ordering': ['-is_daily', 'meal_type', 'name'],
                'indexes': [models.Index(fields=['provider', 'is_available'], name='menus_menu_provide_330c60_idx'), models.Index(fields=['is_daily', 'available_date'], name='menus_menu_is_dail_03641b_idx'), models.Index(fields=['meal_type'], name='menus_menu_meal_ty_843127_idx')],
            },
        ),
    ]
