# Generated by Django 6.0.4 on 2026-04-26 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_alter_menucategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymenu',
            name='is_daily',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailymenu',
            name='meal_type',
            field=models.CharField(choices=[('main', 'Plat principal'), ('starter', 'Entrée'), ('dessert', 'Dessert'), ('drink', 'Boisson'), ('side', 'Accompagnement')], default='main', max_length=20),
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='order_end_time',
            field=models.TimeField(default=datetime.time(10, 30)),
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='order_start_time',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AlterField(
            model_name='menu',
            name='order_end_time',
            field=models.TimeField(default=datetime.time(10, 30), verbose_name='Fin des commandes'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='order_start_time',
            field=models.TimeField(default=datetime.time(8, 0), verbose_name='Début des commandes'),
        ),
    ]
