# Generated by Django 6.0.4 on 2026-04-26 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_dailymenu_is_daily_dailymenu_meal_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailymenu',
            unique_together=set(),
        ),
    ]
